### ISSUE TITLE
Not compatible with Plasma 6

### ISSUE THREAD

**Issue by superuser-does** [xyz32/timekeeper-evolution#2]
The widget now returns this error on loading:

> This Widget was written for an unknown older version of Plasma and is not compatible with Plasma 6. Please contact the widget's author for an updated version.Error loading Applet: package does not exist. Could not open the kde.plasma.timekeeper package required for the Time Keeper Evolution widget.

**Comment by xyz32** [comment]
Hey,
Currently my distro (Fedora) is still on plasma 5. I will have a look at this the moment I get bumped to plasma 6. It seems to be planned for the next release of Fedora.

Thanks.

**Comment by xyz32** [comment]
FYI the latest code now works in Plasam 6.
Some things are still broken though like changing background image and sounds. i will make an official package once those issues are resolved.

**Comment by xyz32** [comment]
The plasmoid should now work with plasma 6.
https://github.com/xyz32/timekeeper-evolution/releases/tag/3.0

**Comment by superuser-does** [comment]
Thank you! I had the following error when installing from the 3.0 release.

> file:///home/USER/.local/share/plasma/plasmoids/com.github.xyz32.timekeeper/contents/ui/main.qml:135:5: Type Sounds unavailable
>
> file:///home/USER/.local/share/plasma/plasmoids/com.github.xyz32.timekeeper/contents/ui/sounds/Sounds.qml:3:1: module "QtQuick3D.SpatialAudio" is not installed

I'm on Nobara Linux, a Fedora distribution. Would you happen to know the name of the package I need? I already have `qt6-qtquick3d` installed.

I greatly appreciate your continued effort and cannot wait to have this widget back on my desktop. It's my own [Calabrese 52](https://one-watch.blogspot.com/2009/02/vincent-calabrese-52.html?m=1). Thanks for everything.

**Comment by xyz32** [comment]
"QtQuick3D.SpatialAudio" is a project for the future, for now I will remove it. I am releasin 3.1 now.
Thanks for the reporting.
