### ISSUE TITLE
General and Support Settings screens are blank in version 3.1

### ISSUE THREAD

**Issue by superuser-does** [xyz32/timekeeper-evolution#3]
It is not possible to select the _General_ or _Support_ options within settings in version 3.1 of the plasmoid.
![image](https://github.com/xyz32/timekeeper-evolution/assets/32982579/660e61a7-5581-4a7d-9f24-50178ff03a5f)

**Comment by xyz32** [comment]
Thanks, should be fixed in 3.2.
